name: health_track
description: "HealthTrack - Flutter app for mood, workout, goals, and health reminders."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.9.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.0
  firebase_crashlytics: ^5.2.2

  # Navigation & State
  go_router: ^14.8.1
  provider: ^6.1.4

  # Networking
  http: ^1.3.0

  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.2.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  firebase_core_platform_interface: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - .env