// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdvu6xpEuobUai0QW9Q_E8fpDCXlVdjDQ',
    appId: '1:469366556738:web:1439878b8b041c590505db',
    messagingSenderId: '469366556738',
    projectId: 'health-track-18',
    authDomain: 'health-track-18.firebaseapp.com',
    storageBucket: 'health-track-18.firebasestorage.app',
    measurementId: 'G-3BXVQ3J6PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLwFky96e29ubeP413khmR3R9oAnAjeO4',
    appId: '1:469366556738:android:490e0ef40cf48d2e0505db',
    messagingSenderId: '469366556738',
    projectId: 'health-track-18',
    storageBucket: 'health-track-18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWCJtsb32ORqsL5cIiiVXeje7vchkHje4',
    appId: '1:469366556738:ios:ca68fbffad541d3f0505db',
    messagingSenderId: '469366556738',
    projectId: 'health-track-18',
    storageBucket: 'health-track-18.firebasestorage.app',
    iosBundleId: 'com.example.healthTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWCJtsb32ORqsL5cIiiVXeje7vchkHje4',
    appId: '1:469366556738:ios:ca68fbffad541d3f0505db',
    messagingSenderId: '469366556738',
    projectId: 'health-track-18',
    storageBucket: 'health-track-18.firebasestorage.app',
    iosBundleId: 'com.example.healthTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdvu6xpEuobUai0QW9Q_E8fpDCXlVdjDQ',
    appId: '1:469366556738:web:38a4aa957ebe9cd70505db',
    messagingSenderId: '469366556738',
    projectId: 'health-track-18',
    authDomain: 'health-track-18.firebaseapp.com',
    storageBucket: 'health-track-18.firebasestorage.app',
    measurementId: 'G-N8P20X0E5V',
  );
}
